name = "BangBangSimulation"
uuid = "adb86412-1c0f-42f5-abb5-12acd1b48164"
version = "1.0.0-DEV"
authors = ["Leonardo Bacciottini"]

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
ConcurrentSim = "6ed1e86c-fcaf-46a9-97e0-2b26a2cdb499"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
QuantumSavory = "2de2e421-972c-4cb5-a0c3-999c85908079"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
ResumableFunctions = "c5292f4c-5179-55e1-98c5-05642aab7184"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
CSV = "0.10.15"
ConcurrentSim = "1.5.0"
DataFrames = "1.8.1"
Graphs = "1.13.1"
Logging = "1.11.0"
Random = "1.11.0"
ResumableFunctions = "1.0.4"
Revise = "3.12.1"
Statistics = "1.11.1"
julia = "1.11.7"

[extras]
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Distributed"]
